In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import mean_squared_error, r2_score

In [5]:
data=pd.read_csv("/content/Breast_cancer_data.csv")

In [6]:
data.head()

mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   diagnosis  
0          0  
1          0  
2          0  
3          0  
4          0

In [11]:
 # Step 1: Split the data into features (X) and target (y)
 x= data.drop(columns=["diagnosis"])  # Replace with the actual target column name
 y = data["diagnosis"]

In [45]:
# Step 2: Split the data into training and testing sets
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8)

***Linear Regression***

In [13]:
from sklearn.linear_model import LinearRegression
regression=LinearRegression()

In [14]:
regression.fit(x_train,y_train)

LinearRegression()

In [15]:
lin_Predication=regression.predict(x_test)

In [16]:
regression.score(x,y)

0.6454424921932845

In [55]:
mse=mean_squared_error(y_test,lin_Predication)
r2=r2_score(y_test,lin_Predication)

In [56]:
print(mse)

0.3845982618008692


In [57]:
print(r2)

-0.6528568155965926


***KNN***

In [17]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5) #here K=5

In [18]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [19]:
k_predictions=knn.predict(x_test)

In [20]:
k_cm=confusion_matrix(y_test,k_predictions)
k_ac=accuracy_score(y_test,k_predictions)

In [49]:
mse=mean_squared_error(y_test,k_predictions)
r2=r2_score(y_test,k_predictions)

In [21]:
print(k_cm)

[[32  8]
 [ 6 68]]


In [22]:
print(k_ac)

0.8771929824561403


In [50]:
print(mse)

0.43859649122807015


In [51]:
print(r2)

-0.8849206349206349


***Logistc Rigression***

In [23]:
from sklearn.linear_model import LogisticRegression
log_model=LogisticRegression()

In [24]:
log_model.fit(x_train,y_train)

LogisticRegression()

In [25]:
Log_predictions=log_model.predict(x_test)

In [26]:
log_cm=confusion_matrix(y_test,Log_predictions)
log_ac=accuracy_score(y_test,Log_predictions)

In [46]:
mse=mean_squared_error(y_test,Log_predictions)
r2=r2_score(y_test,Log_predictions)

In [27]:
print(log_cm)

[[34  6]
 [ 2 72]]


In [28]:
print(log_ac)

0.9298245614035088


In [47]:
print(mse)

0.42105263157894735


In [48]:
print(r2)

-0.8095238095238095


***Decision Tree Classification***

In [29]:
from sklearn.tree import DecisionTreeClassifier
tree_classifier=DecisionTreeClassifier()

In [30]:
tree_classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [32]:
tree_predictions=tree_classifier.predict(x_test)

In [33]:
DTC_cm=confusion_matrix(y_test,tree_predictions)
DTC_ac=accuracy_score(y_test,tree_predictions)

In [40]:
mse=mean_squared_error(y_test,tree_predictions)
r2=r2_score(y_test,tree_predictions)

In [41]:
print(DTC_cm)

[[35  5]
 [ 4 70]]


In [42]:
print(DTC_ac)

0.9210526315789473


In [43]:
print(mse)

0.07894736842105263


In [44]:
print(r2)

0.6533783783783784


***Random Forest Classification***

In [61]:
from sklearn.ensemble import RandomForestClassifier
forest_classifier=RandomForestClassifier()

In [62]:
forest_classifier.fit(x_train,y_train)

RandomForestClassifier()

In [63]:
forest_predictions=forest_classifier.predict(x_test)

In [64]:
RFC_cm=confusion_matrix(y_test,forest_predictions)
RFC_ac=accuracy_score(y_test,forest_predictions)

In [68]:
mse=mean_squared_error(y_test,forest_predictions)
r2=r2_score(y_test,forest_predictions)

In [66]:
print(RFC_cm)

[[36  6]
 [ 6 66]]


In [67]:
print(RFC_ac)

0.8947368421052632


In [69]:
print(mse)

0.10526315789473684


In [70]:
print(r2)

0.5476190476190477


***Decision Tree Regression***

In [71]:
from sklearn.tree import DecisionTreeRegressor
Tree_Reg=DecisionTreeRegressor()

In [72]:
Tree_Reg.fit(x_train,y_train)

DecisionTreeRegressor()

In [86]:
DTR_prediction=Tree_Reg.predict(x_test)

In [87]:
DTR_cm=confusion_matrix(y_test,DTR_prediction)
DTR_ac=accuracy_score(y_test,DTR_prediction)

In [88]:
mse=mean_squared_error(y_test,DTR_prediction)
r2=r2_score(y_test,DTR_prediction)

In [89]:
print(DTR_cm)

[[36  6]
 [10 62]]


In [90]:
print(DTR_ac)

0.8596491228070176


In [91]:
print(mse)

0.14035087719298245


In [92]:
print(r2)

0.39682539682539686


***Random Forest Rigression***

In [83]:
from sklearn.ensemble import RandomForestRegressor
R_forest_regressor=RandomForestRegressor()

In [84]:
R_forest_regressor.fit(x_train,y_train)

RandomForestRegressor()

In [93]:
RFR_predictions=R_forest_regressor.predict(x_test)

In [95]:
mse=mean_squared_error(y_test,RFR_predictions)
r2=r2_score(y_test,RFR_predictions)

In [98]:
print(mse)

0.08711754385964912


In [99]:
print(r2)

0.6256019841269842


***Support Vector Machine (SVM)***

In [102]:
from sklearn.svm import SVC
svc_model=SVC()

In [103]:
svc_model.fit(x_train,y_train)

SVC()

In [104]:
svc_predictions=svc_model.predict(x_test)

In [105]:
svc_cm=confusion_matrix(y_test,svc_predictions)
svc_ac=accuracy_score(y_test,svc_predictions)

In [106]:
print(svc_cm)

[[29 13]
 [ 3 69]]


In [107]:
print(svc_ac)

0.8596491228070176


In [111]:
svc_mse=mean_squared_error(y_test,svc_predictions)
svc_r2=r2_score(y_test,svc_predictions)

In [112]:
print(svc_mse)

0.14035087719298245


In [113]:
print(svc_r2)

0.39682539682539686


***Naive Bayes***

In [114]:
from sklearn.naive_bayes import GaussianNB
nb_classifier=GaussianNB()

In [115]:
nb_classifier.fit(x_train,y_train)

GaussianNB()

In [116]:
nb_predictions=nb_classifier.predict(x_test)

In [117]:
nb_cm=confusion_matrix(y_test,nb_predictions)
nb_ac=accuracy_score(y_test,nb_predictions)

In [118]:
print(nb_cm)

[[31 11]
 [ 4 68]]


In [119]:
print(nb_ac)

0.868421052631579


In [120]:
nb_mse=mean_squared_error(y_test,nb_predictions)
nb_r2=r2_score(y_test,nb_predictions)

In [121]:
print(nb_mse)

0.13157894736842105


In [122]:
print(nb_r2)

0.43452380952380953


***Principal Component Analaysis(PCA)***

In [125]:
from sklearn.decomposition import PCA
pca=PCA(n_components=5)

In [126]:
x_reduced_train=pd.DataFrame(pca.fit_transform(x_train))
x_reduced_test=pd.DataFrame(pca.fit_transform(x_test))

In [135]:
x_train.shape

(455, 5)

In [136]:
x_reduced_train.shape

(455, 5)

In [137]:
knn.fit(x_reduced_train,y_train)

KNeighborsClassifier()

In [138]:
pca_prediction=knn.predict(x_reduced_test)

In [139]:
pca_cm=confusion_matrix(y_test,pca_prediction)
pca_ac=accuracy_score(y_test,pca_prediction)

In [140]:
print(pca_cm)

[[31 11]
 [11 61]]


In [141]:
print(pca_ac)

0.8070175438596491


***Boosting accuracy using AdaBoost***





In [142]:
from sklearn.ensemble import AdaBoostClassifier

In [143]:
classifier=AdaBoostClassifier(DecisionTreeClassifier(max_depth=1),n_estimators=20)

In [145]:
classifier.fit(x_train,y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1),
                   n_estimators=20)

In [146]:
AB_predictions=classifier.predict(x_test)

In [147]:
AB_cm=confusion_matrix(y_test,AB_predictions)
AB_ac=accuracy_score(y_test,AB_predictions)

In [148]:
print(AB_cm)

[[35  7]
 [ 7 65]]


In [149]:
print(AB_ac)

0.8771929824561403


***Hist Gradient Boosting Classifier***

In [150]:
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier

/usr/local/lib/python3.10/dist-packages/sklearn/experimental/enable_hist_gradient_boosting.py:16: UserWarning: Since version 1.0, it is not needed to import enable_hist_gradient_boosting anymore. HistGradientBoostingClassifier and HistGradientBoostingRegressor are now stable and can be normally imported from sklearn.ensemble.
  warnings.warn(


In [151]:
# Create and fit a HistGradientBoostingClassifier
clf = HistGradientBoostingClassifier()

In [153]:
# Make predictions on the test set
clf.fit(x_train, y_train)

HistGradientBoostingClassifier()

In [158]:
HGBC_pred = clf.predict(x_test)

In [165]:
HGBC_mse=mean_squared_error(y_test,HGBC_pred )
HGBC_r2=r2_score(y_test,HGBC_pred )

In [166]:
print(HGBC_mse)

0.11403508771929824


In [167]:
print(HGBC_r2)

0.5099206349206349


In [159]:
HGBC_cm=confusion_matrix(y_test,HGBC_pred)
HGBC_ac=accuracy_score(y_test,HGBC_pred)

In [160]:
print(HGBC_cm)

[[36  6]
 [ 7 65]]


In [161]:
print(HGBC_ac)

0.8859649122807017
